[tools]
tuist = { version = "4.128.3", os = ["macos"] }
swiftformat = { version = "0.58.6", os = ["macos"] }
swiftlint = { version = "0.62.2", os = ["macos"] }
sentry-cli = { version = "latest", os = ["macos"] }
pipx = { version = "latest", os = ["macos", "linux"] }
"pipx:infomaniak/importloco" = { version = "1.2.0", os = ["macos", "linux"] }