name: Validate localization files

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: infomaniak/.github/.github/workflows/validate-localization.yml@feat/add-workflows
    with:
      localizable_path: "kDrive/Resources"
      main_target_localizable_path: "kDrive/Resources"
    secrets: inherit
